# Generated by Django 5.2.5 on 2026-06-12 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_injuries_meal_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='weekly_workout_goal',
            field=models.PositiveSmallIntegerField(default=3, help_text="Nombre de séances visées par semaine (anneau d'objectif)."),
        ),
        migrations.CreateModel(
            name='PlanFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('meal', 'Plan repas'), ('workout', 'Plan sport')], max_length=10)),
                ('plan_id', models.CharField(blank=True, max_length=64)),
                ('liked', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plan_feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'plan_type'], name='plan_feedba_user_id_116e23_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeightLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'weight_log',
                'ordering': ['-logged_at'],
                'indexes': [models.Index(fields=['user', 'logged_at'], name='weight_log_user_id_93300b_idx')],
            },
        ),
    ]
