# Generated by Django 5.2.5 on 2026-04-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=12)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bmi_calculated', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GymSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gym_session_duration_hours', models.FloatField(blank=True, null=True)),
                ('gym_calories_burned', models.IntegerField(blank=True, null=True)),
                ('gym_workout_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gym_max_bpm', models.IntegerField(blank=True, null=True)),
                ('gym_avg_bpm', models.IntegerField(blank=True, null=True)),
                ('gym_resting_bpm', models.IntegerField(blank=True, null=True)),
                ('gym_fat_percentage', models.FloatField(blank=True, null=True)),
                ('gym_water_intake_liters', models.FloatField(blank=True, null=True)),
                ('gym_workout_frequency_days_week', models.IntegerField(blank=True, null=True)),
                ('gym_experience_level', models.IntegerField(blank=True, null=True)),
                ('calories_per_hour', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gym_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActivitePhysique',
            fields=[
                ('patient', models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patient')),
                ('physical_activity_level', models.CharField(blank=True, max_length=50, null=True)),
                ('weekly_exercice_hours', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activite_physique',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('patient', models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patient')),
                ('daily_caloric_intake', models.IntegerField(blank=True, null=True)),
                ('dietary_restrictions', models.CharField(blank=True, max_length=255, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_cuisine', models.CharField(blank=True, max_length=100, null=True)),
                ('diet_recommendation', models.CharField(blank=True, max_length=255, null=True)),
                ('adherence_to_diet_plan', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nutrition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sante',
            fields=[
                ('patient', models.OneToOneField(db_column='patient_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.patient')),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.IntegerField(blank=True, null=True)),
                ('disease_type', models.CharField(blank=True, max_length=100, null=True)),
                ('glucose', models.FloatField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'sante',
                'managed': False,
            },
        ),
    ]
