# Generated by Django 5.2.5 on 2026-05-21 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pendingchange_and_supervisors_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(blank=True, choices=[('weight_loss', 'Perdre du poids'), ('muscle_gain', 'Prendre du muscle'), ('endurance', 'Améliorer mon endurance'), ('general_health', 'Maintenir ma forme')], max_length=30)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Débutant'), ('intermediate', 'Intermédiaire'), ('advanced', 'Avancé')], max_length=20)),
                ('dietary_restrictions', models.CharField(choices=[('none', 'Aucune'), ('vegetarian', 'Végétarien'), ('vegan', 'Végan'), ('gluten_free', 'Sans gluten'), ('lactose_free', 'Sans lactose')], default='none', max_length=20)),
                ('allergies', models.TextField(blank=True, help_text='Allergies séparées par virgules')),
                ('equipment_available', models.TextField(blank=True, help_text='Équipement séparé par virgules')),
                ('daily_calorie_target', models.PositiveIntegerField(blank=True, null=True)),
                ('onboarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_profile',
            },
        ),
        migrations.RenameIndex(
            model_name='pendingchange',
            new_name='api_pending_status_db7ad0_idx',
            old_name='api_pending_status_idx',
        ),
        migrations.RenameIndex(
            model_name='pendingchange',
            new_name='api_pending_table_n_505b0e_idx',
            old_name='api_pending_table_record_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
