# Generated by Django 5.2.5 on 2026-06-10 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_exercise_foodlog_mealentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done_at', models.DateTimeField(auto_now_add=True)),
                ('focus', models.CharField(choices=[('upper', 'Haut du corps'), ('lower', 'Bas du corps'), ('full', 'Full body'), ('cardio', 'Cardio'), ('hiit', 'HIIT'), ('mobility', 'Mobilité / récupération'), ('other', 'Autre')], default='other', max_length=20)),
                ('duration_min', models.PositiveSmallIntegerField(default=30)),
                ('estimated_calories', models.PositiveIntegerField(blank=True, null=True)),
                ('exercises_done', models.JSONField(default=list)),
                ('difficulty_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-done_at'],
            },
        ),
    ]
