# Generated by Django 5.2.5 on 2026-06-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workoutsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='injuries',
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Blessures / limitations (liste JSON, ex. ["genou", "dos"])',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='meal_budget',
            field=models.PositiveIntegerField(
                blank=True,
                help_text='Budget repas hebdomadaire optionnel (€)',
                null=True,
            ),
        ),
    ]
